### ISSUE TITLE
Compilation error after update to Xcode 7.3

### ISSUE THREAD

**Issue by nico75005** [auth0/Lock-Facebook.iOS#10]
I just installed Xcode 7.3 and I got the following compilation errors that I didn't have previously. I didn't touch anything else, my pod is loaded with `pod 'Lock-Facebook', '~> 2.1'`:

`Project/Pods/Lock-Facebook/LockFacebook/FacebookProvider.m:25:9: Could not build module 'FBSDKCoreKit'`

and

`Project/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.h:26:10: Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'`

What's wrong?

**Comment by hzalaz** [comment]
@nico75005 did you tried https://github.com/auth0/Lock-Facebook.iOS#build-issues-with-cocoapods?

**Comment by nico75005** [comment]
Yes, here is my podfile. With xcode 7.2 it was fine and since I updated to 7.3 I got those errors.

```
pod 'Lock', '~> 1.23'
pod 'Lock-Facebook', '~> 2.1'

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end
```

**Comment by hzalaz** [comment]
@nico75005 try updating FB SDK to the latest version (`pod update`) or adding it alone and see what happens. This seems to be related to how the FB SDK library is coded.

**Comment by nico75005** [comment]
@hzalaz when I change my Podfile for the following:

```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

pod 'Lock', '~> 1.23'
#pod 'Lock-Facebook', '~> 2.1'

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end
```

and I do a `pod update` and I comment everything related to Lock-Facebook such as

```
let facebookAuth = A0FacebookAuthenticator.newAuthenticatorWithPermissions(["public_profile", "email"])
```

then no more compilation error.

**Comment by nico75005** [comment]
@hzalaz 

The problem is still there...
Didn't find a solution, and as I said previously, when using `FBSDKCoreKit` & `FBSDKLoginKit` I don't get those errors. It's only when I'm adding `Lock-Facebook` to my `pod` file. I'm using the latest version (`Using Lock-Facebook (2.2.1)`).

Any idea?

![screen shot 2016-04-07 at 08 37 56](https://cloud.githubusercontent.com/assets/1647328/14332231/9a831b0a-fc9c-11e5-8831-edd12dda831c.png)

**Comment by malshash** [comment]
Changing my import to the following seems to have fixed the issue.

```
@import LockFacebook;
```
